package com.unistart.entities;
// Generated Sep 17, 2017 1:40:06 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name = "Candidate", schema = "dbo", catalog = "University")
public class Candidate implements java.io.Serializable {

	private int id;
	private String username;
	private String name;
	private String password;
	private Double gpa;
	private String avatar;
	private String email;
	private Boolean isActive;
	private Set<ReviewLike> reviewLikes = new HashSet<ReviewLike>(0);

	public Candidate() {
	}

	public Candidate(int id, String username, String name, String password, String email) {
		this.id = id;
		this.username = username;
		this.name = name;
		this.password = password;
		this.email = email;
	}

	public Candidate(int id, String username, String name, String password, Double gpa, String avatar, String email,
			Boolean isActive, Set<ReviewLike> reviewLikes) {
		this.id = id;
		this.username = username;
		this.name = name;
		this.password = password;
		this.gpa = gpa;
		this.avatar = avatar;
		this.email = email;
		this.isActive = isActive;
		this.reviewLikes = reviewLikes;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Gpa", precision = 53, scale = 0)
	public Double getGpa() {
		return this.gpa;
	}

	public void setGpa(Double gpa) {
		this.gpa = gpa;
	}

	@Column(name = "Avatar")
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "Email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<ReviewLike> getReviewLikes() {
		return this.reviewLikes;
	}

	public void setReviewLikes(Set<ReviewLike> reviewLikes) {
		this.reviewLikes = reviewLikes;
	}

}
