package com.unistart.entities;
// Generated Sep 21, 2017 4:14:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MajorUniversity generated by hbm2java
 */
@Entity
@Table(name = "Major_University", schema = "dbo", catalog = "University")
public class MajorUniversity implements java.io.Serializable {

	private int id;
	private Major major;
	private University university;
	private Set<BlockMajorUniversity> blockMajorUniversities = new HashSet<BlockMajorUniversity>(0);

	public MajorUniversity() {
	}

	public MajorUniversity(int id) {
		this.id = id;
	}

	public MajorUniversity(int id, Major major, University university,
			Set<BlockMajorUniversity> blockMajorUniversities) {
		this.id = id;
		this.major = major;
		this.university = university;
		this.blockMajorUniversities = blockMajorUniversities;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MajorId")
	public Major getMajor() {
		return this.major;
	}

	public void setMajor(Major major) {
		this.major = major;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UniversityId")
	public University getUniversity() {
		return this.university;
	}

	public void setUniversity(University university) {
		this.university = university;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "majorUniversity")
	public Set<BlockMajorUniversity> getBlockMajorUniversities() {
		return this.blockMajorUniversities;
	}

	public void setBlockMajorUniversities(Set<BlockMajorUniversity> blockMajorUniversities) {
		this.blockMajorUniversities = blockMajorUniversities;
	}

}
