package com.unistart.entities;
// Generated Sep 25, 2017 1:40:32 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * MajorUniversity generated by hbm2java
 */
@Entity
@Table(name = "Major_University", schema = "dbo", catalog = "University")
public class MajorUniversity implements java.io.Serializable {

	private int id;
//	@JsonBackReference
	private Major major;
	@JsonBackReference
	private University university;
	private Set<BlockMajorUniversity> blockMajorUniversities = new HashSet<BlockMajorUniversity>(0);

	public MajorUniversity() {
	}

	public MajorUniversity(int id) {
		this.id = id;
	}

	public MajorUniversity(int id, Major major, University university, byte[] majorUniversitiesKey,
			Set<BlockMajorUniversity> blockMajorUniversities) {
		this.id = id;
		this.major = major;
		this.university = university;
		this.blockMajorUniversities = blockMajorUniversities;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MajorId")
	public Major getMajor() {
		return this.major;
	}

	public void setMajor(Major major) {
		this.major = major;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "UniversityId")
	public University getUniversity() {
		return this.university;
	}

	public void setUniversity(University university) {
		this.university = university;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "majorUniversity")
	public Set<BlockMajorUniversity> getBlockMajorUniversities() {
		return this.blockMajorUniversities;
	}

	public void setBlockMajorUniversities(Set<BlockMajorUniversity> blockMajorUniversities) {
		this.blockMajorUniversities = blockMajorUniversities;
	}

}
