package com.unistart.entities;
// Generated Sep 17, 2017 1:40:06 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Mbtigroup generated by hbm2java
 */
@Entity
@Table(name = "MBTIGroup", schema = "dbo", catalog = "University")
public class Mbtigroup implements java.io.Serializable {

	private int id;
	private Serializable mbtigroupName;
	private Boolean isActive;
	private Set<Mbtiquestion> mbtiquestions = new HashSet<Mbtiquestion>(0);

	public Mbtigroup() {
	}

	public Mbtigroup(int id) {
		this.id = id;
	}

	public Mbtigroup(int id, Serializable mbtigroupName, Boolean isActive, Set<Mbtiquestion> mbtiquestions) {
		this.id = id;
		this.mbtigroupName = mbtigroupName;
		this.isActive = isActive;
		this.mbtiquestions = mbtiquestions;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MBTIGroupName")
	public Serializable getMbtigroupName() {
		return this.mbtigroupName;
	}

	public void setMbtigroupName(Serializable mbtigroupName) {
		this.mbtigroupName = mbtigroupName;
	}

	@Column(name = "isActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbtigroup")
	public Set<Mbtiquestion> getMbtiquestions() {
		return this.mbtiquestions;
	}

	public void setMbtiquestions(Set<Mbtiquestion> mbtiquestions) {
		this.mbtiquestions = mbtiquestions;
	}

}
