package com.unistart.entities;
// Generated Sep 20, 2017 9:59:41 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mbtitype generated by hbm2java
 */
@Entity
@Table(name = "MBTIType", schema = "dbo", catalog = "University")
public class Mbtitype implements java.io.Serializable {

	private int id;
	private Serializable mbtitypeName;
	private Serializable description;
	private boolean isActive;
	private Set<Mbtiresult> mbtiresults = new HashSet<Mbtiresult>(0);
	private Set<Mbtiresult> mbtiresults_1 = new HashSet<Mbtiresult>(0);
	private Set<MajorMbti> majorMbtis = new HashSet<MajorMbti>(0);
	private Set<MajorMbti> majorMbtis_1 = new HashSet<MajorMbti>(0);

	public Mbtitype() {
	}

	public Mbtitype(int id, boolean isActive) {
		this.id = id;
		this.isActive = isActive;
	}

	public Mbtitype(int id, Serializable mbtitypeName, Serializable description, boolean isActive,
			Set<Mbtiresult> mbtiresults, Set<Mbtiresult> mbtiresults_1, Set<MajorMbti> majorMbtis,
			Set<MajorMbti> majorMbtis_1) {
		this.id = id;
		this.mbtitypeName = mbtitypeName;
		this.description = description;
		this.isActive = isActive;
		this.mbtiresults = mbtiresults;
		this.mbtiresults_1 = mbtiresults_1;
		this.majorMbtis = majorMbtis;
		this.majorMbtis_1 = majorMbtis_1;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MBTITypeName")
	public Serializable getMbtitypeName() {
		return this.mbtitypeName;
	}

	public void setMbtitypeName(Serializable mbtitypeName) {
		this.mbtitypeName = mbtitypeName;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbtitype")
	public Set<Mbtiresult> getMbtiresults() {
		return this.mbtiresults;
	}

	public void setMbtiresults(Set<Mbtiresult> mbtiresults) {
		this.mbtiresults = mbtiresults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbtitype")
	public Set<Mbtiresult> getMbtiresults_1() {
		return this.mbtiresults_1;
	}

	public void setMbtiresults_1(Set<Mbtiresult> mbtiresults_1) {
		this.mbtiresults_1 = mbtiresults_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbtitype")
	public Set<MajorMbti> getMajorMbtis() {
		return this.majorMbtis;
	}

	public void setMajorMbtis(Set<MajorMbti> majorMbtis) {
		this.majorMbtis = majorMbtis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbtitype")
	public Set<MajorMbti> getMajorMbtis_1() {
		return this.majorMbtis_1;
	}

	public void setMajorMbtis_1(Set<MajorMbti> majorMbtis_1) {
		this.majorMbtis_1 = majorMbtis_1;
	}

}
