package com.unistart.entities;
// Generated Sep 17, 2017 1:40:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Provider generated by hbm2java
 */
@Entity
@Table(name = "Provider", schema = "dbo", catalog = "University")
public class Provider implements java.io.Serializable {

	private ProviderId id;
	private User user;

	public Provider() {
	}

	public Provider(ProviderId id, User user) {
		this.id = id;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "providerId", column = @Column(name = "ProviderID", nullable = false)),
			@AttributeOverride(name = "providerName", column = @Column(name = "ProviderName", nullable = false)) })
	public ProviderId getId() {
		return this.id;
	}

	public void setId(ProviderId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
