package com.unistart.entities;
// Generated Sep 21, 2017 4:14:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Provider generated by hbm2java
 */
@Entity
@Table(name = "Provider", schema = "dbo", catalog = "University")
public class Provider implements java.io.Serializable {

	private ProviderId id;
	private Users users;
	private byte[] users_1;

	public Provider() {
	}

	public Provider(ProviderId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public Provider(ProviderId id, Users users, byte[] users_1) {
		this.id = id;
		this.users = users;
		this.users_1 = users_1;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "providerId", column = @Column(name = "ProviderID", nullable = false)),
			@AttributeOverride(name = "providerName", column = @Column(name = "ProviderName", nullable = false)) })
	public ProviderId getId() {
		return this.id;
	}

	public void setId(ProviderId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "users")
	public byte[] getUsers_1() {
		return this.users_1;
	}

	public void setUsers_1(byte[] users_1) {
		this.users_1 = users_1;
	}

}
