package com.unistart.entities;
// Generated Sep 20, 2017 9:59:41 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProviderId generated by hbm2java
 */
@Embeddable
public class ProviderId implements java.io.Serializable {

	private Serializable providerId;
	private Serializable providerName;

	public ProviderId() {
	}

	public ProviderId(Serializable providerId, Serializable providerName) {
		this.providerId = providerId;
		this.providerName = providerName;
	}

	@Column(name = "ProviderID", nullable = false)
	public Serializable getProviderId() {
		return this.providerId;
	}

	public void setProviderId(Serializable providerId) {
		this.providerId = providerId;
	}

	@Column(name = "ProviderName", nullable = false)
	public Serializable getProviderName() {
		return this.providerName;
	}

	public void setProviderName(Serializable providerName) {
		this.providerName = providerName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProviderId))
			return false;
		ProviderId castOther = (ProviderId) other;

		return ((this.getProviderId() == castOther.getProviderId()) || (this.getProviderId() != null
				&& castOther.getProviderId() != null && this.getProviderId().equals(castOther.getProviderId())))
				&& ((this.getProviderName() == castOther.getProviderName())
						|| (this.getProviderName() != null && castOther.getProviderName() != null
								&& this.getProviderName().equals(castOther.getProviderName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProviderId() == null ? 0 : this.getProviderId().hashCode());
		result = 37 * result + (getProviderName() == null ? 0 : this.getProviderName().hashCode());
		return result;
	}

}
