package com.unistart.entities;
// Generated Sep 20, 2017 9:59:41 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * University generated by hbm2java
 */
@Entity
@Table(name = "University", schema = "dbo", catalog = "University")
public class University implements java.io.Serializable {

	private int id;
	private String code;
	private String name;
	private String email;
	private String phone;
	private String logo;
	private String description;
	private String image;
	private Integer priority;
	private Boolean isActive;
	private Set<Location> locations = new HashSet<Location>(0);
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<Review> reviews_1 = new HashSet<Review>(0);
	private Set<Users> userses_1 = new HashSet<Users>(0);
	private Set<Location> locations_1 = new HashSet<Location>(0);
	private Set<MajorUniversity> majorUniversities = new HashSet<MajorUniversity>(0);
	private Set<MajorUniversity> majorUniversities_1 = new HashSet<MajorUniversity>(0);

	public University() {
	}

	public University(int id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	public University(String code, String name, String email, String phone, String logo,
			String description, String image, boolean isActive) {
		super();
		this.code = code;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.logo = logo;
		this.description = description;
		this.image = image;
		this.isActive = isActive; 
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Code", nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Logo")
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "Priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<Location> locations) {
		this.locations = locations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<Review> getReviews_1() {
		return this.reviews_1;
	}

	public void setReviews_1(Set<Review> reviews_1) {
		this.reviews_1 = reviews_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<Users> getUserses_1() {
		return this.userses_1;
	}

	public void setUserses_1(Set<Users> userses_1) {
		this.userses_1 = userses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<Location> getLocations_1() {
		return this.locations_1;
	}

	public void setLocations_1(Set<Location> locations_1) {
		this.locations_1 = locations_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<MajorUniversity> getMajorUniversities() {
		return this.majorUniversities;
	}

	public void setMajorUniversities(Set<MajorUniversity> majorUniversities) {
		this.majorUniversities = majorUniversities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<MajorUniversity> getMajorUniversities_1() {
		return this.majorUniversities_1;
	}

	public void setMajorUniversities_1(Set<MajorUniversity> majorUniversities_1) {
		this.majorUniversities_1 = majorUniversities_1;
	}

}
